# Aljabar Matrix
###Tidak mengerjakan tidak boleh masuk
* Berikan pengertian apa itu Aljabar matrix
* Buatlah Matrix A(3x3),B(2x3),C(3x2)
* Operasi Matrix
  * Penjumlahan
  * Perkalian
  * Pengurangan
  * Tranpose Matrix
* Buat program untuk mengkalikan Matrix A dengan Matrix B tidak menggunakan '@'

Pengertian Matrix: Matrix merupakan suatu kumpulan bilangan sejumlah m x n yang disusun menjadi m baris dan n kolom.

In [ ]:
import numpy as np

In [ ]:
# Matrix
A = np.array([[1,3,9],[3,-2,6],[9,4,1]]) # matrix 3x3
B = np.array([[1,7,5],[2,4,5],[1,-1,4]]) # matrix 3x3
C = np.array([[3,2],[-1,2],[3,5]]) # matrix 3x2
D = np.array([[2,4,8],[2,-1,5],[-8,5,2]]) # matrix 3x3
E = (A+B)
F = 2*(A)
G = A @ C

In [ ]:
print(f"Matrix A 3x3: \n{A}")
print(f" Matrix B 3x3: \n{B}")
print(f"Matrix C 3x2: \n{C}")
print(f"Matrix D 3x3: \n{D}")

Matrix A 3x3: 
[[ 1  3  9]
 [ 3 -2  6]
 [ 9  4  1]]
 Matrix B 3x3: 
[[ 1  7  5]
 [ 2  4  5]
 [ 1 -1  4]]
Matrix C 3x2: 
[[ 3  2]
 [-1  2]
 [ 3  5]]
Matrix D 3x3: 
[[ 2  4  8]
 [ 2 -1  5]
 [-8  5  2]]


#Operasi Penjumlahan Matrix

In [ ]:
# Matrix A+B
E = (A+B)
print(f"Matrix E =\n{E}")

Matrix E =
[[ 2 10 14]
 [ 5  2 11]
 [10  3  5]]


#Operasi Perkalian Matrix

In [ ]:
F = 2*(A)

print(f"Perkalian 2 * Matrix F =\n{F}")

Perkalian 2 * Matrix F =
[[ 2  6 18]
 [ 6 -4 12]
 [18  8  2]]


In [ ]:
# Matrix A x C
G = A @ C
print(f"Matrix G =\n{G}")
print(f"Ukuran Matrix = {G.shape}")

Matrix G =
[[27 53]
 [29 32]
 [26 31]]
Ukuran Matrix = (3, 2)


#Operasi Pengurangan Matrix

In [ ]:
# Matrix A - B
H  = A - B
print(f"Matrix G =\n{H}")

Matrix G =
[[ 0 -4  4]
 [ 1 -6  1]
 [ 8  5 -3]]


#Cek Persamaan
Matrix A(BxC) = Matrix (AxB)C

In [ ]:
Matrix1 = A@(B@C)
Matrix2 = (A@B)@C
Matrix1 == Matrix2

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

Matrix c(AB) = Matrix (cA)B = Matrix A(cB)

In [ ]:
c = 2
Matrix_3 = c*(A@B)
Matrix_4 = (c*A)@B
Matrix_5 = A@(c*B)
print(Matrix_3)
print()
print(Matrix_4)
print()
print(Matrix_5)

[[ 32  20 112]
 [ 10  14  58]
 [ 36 156 138]]

[[ 32  20 112]
 [ 10  14  58]
 [ 36 156 138]]

[[ 32  20 112]
 [ 10  14  58]
 [ 36 156 138]]


#Tranpose Matrix
Anggap Baris = m, Kolom = n

=> C = A_trans @ A

=> (n x m) @ (m x n) = n * n

contoh: [2 x 3] @ [3 x 2] = [2 x 2]

=> C = A @ A_trans

=> (m x n) @ (n x m) = m x m

contoh: [3 x 2] @ [2 x 3] = [3 x 3]

In [ ]:
# Contoh dengan Martrix 3x3

A_tran = A.transpose()
print('Matrik A sebelum di transpose=\n', A)
print()
print('Matrik A setelah di transpose=\n',A_tran)
print('Ordo A_transpose adalah',A_tran.shape)
print()
Z = A_tran @ A
print('Z = A_transpose x A =\n',Z)
print('Ordo Z adalah',Z.shape)
print()
P=A @ A_tran
print('P = A_transpose x A =\n',P)
print('Ordo P adalah',P.shape)

Matrik A sebelum di transpose=
 [[ 1  3  9]
 [ 3 -2  6]
 [ 9  4  1]]

Matrik A setelah di transpose=
 [[ 1  3  9]
 [ 3 -2  4]
 [ 9  6  1]]
Ordo A_transpose adalah (3, 3)

Z = A_transpose x A =
 [[ 91  33  36]
 [ 33  29  19]
 [ 36  19 118]]
Ordo Z adalah (3, 3)

P = A_transpose x A =
 [[91 51 30]
 [51 49 25]
 [30 25 98]]
Ordo P adalah (3, 3)


In [ ]:
# Soal dengan Matrix 3x2

Matrix_A = np.array([[-1,2,3],[3,2,1]])

Matrix_A_Trans = Matrix_A.transpose()
print('Matrix_A sebelum di transpose=\n', Matrix_A)
print()

print('Matrix A setelah di transpose=\n',Matrix_A_Trans)
print('Ordo Matrix_A_Transpose adalah',Matrix_A_Trans.shape)
print()

Matrix_Z = Matrix_A_Trans @ Matrix_A
print('Matrix_Z = Matrix_A_Transpose x Matrix_A =\n',Matrix_Z)
print('Ordo Z adalah',Z.shape)
print()

Matrix_P = Matrix_A @ Matrix_A_Trans
print('P = A_transpose x A =\n',Matrix_P)
print('ordo Matrix P adalah',Matrix_P.shape)

Matrix_A sebelum di transpose=
 [[-1  2  3]
 [ 3  2  1]]

Matrix A setelah di transpose=
 [[-1  3]
 [ 2  2]
 [ 3  1]]
Ordo Matrix_A_Transpose adalah (3, 2)

Matrix_Z = Matrix_A_Transpose x Matrix_A =
 [[10  4  0]
 [ 4  8  8]
 [ 0  8 10]]
Ordo Z adalah (3, 3)

P = A_transpose x A =
 [[14  4]
 [ 4 14]]
ordo Matrix P adalah (2, 2)


#Program untuk mengkalikan Matrix A dengan Matrix B Secara Manual tidak menggunakan ‘@’

In [ ]:
Matrix_1 = [[2,4,7],
            [5,-1,4],
            [7,6,3]]

Matrix_2 = [[7,5,3],
            [4,6,9],
            [1,-3,2]]
Result = []

print(f" Matrix_1 = {Matrix_1}")
print()
print(f" Matrix_2 = {Matrix_2}")

def multiply_matrix(matrix1,matrix2):
  result = [[0,0,0],[0,0,0],[0,0,0]] # Menginisialisasikan dulu matrix dengan semua value 0

  for i in range(len(Matrix_1)):
    for j in range(len(Matrix_2[0])):
      for k in range(len(Matrix_2)):
        result[i][j] += Matrix_1[i][k] * Matrix_2[k][j]
        print(result)
        print("Matrix 1 : ", Matrix_1[i][k])
        print("Matrix 2 : ", Matrix_2[k][j])
  return result

hasil = multiply_matrix(Matrix_1,Matrix_2)
print()
print(f"Hasil perkalian Matrix_1 dan Matrix 2 = {hasil}")
print()
print(f"Pembuktian untuk Matrix A @ B =\n{A @ B}")

 Matrix_1 = [[2, 4, 7], [5, -1, 4], [7, 6, 3]]

 Matrix_2 = [[7, 5, 3], [4, 6, 9], [1, -3, 2]]
[[14, 0, 0], [0, 0, 0], [0, 0, 0]]
Matrix 1 :  2
Matrix 2 :  7
[[30, 0, 0], [0, 0, 0], [0, 0, 0]]
Matrix 1 :  4
Matrix 2 :  4
[[37, 0, 0], [0, 0, 0], [0, 0, 0]]
Matrix 1 :  7
Matrix 2 :  1
[[37, 10, 0], [0, 0, 0], [0, 0, 0]]
Matrix 1 :  2
Matrix 2 :  5
[[37, 34, 0], [0, 0, 0], [0, 0, 0]]
Matrix 1 :  4
Matrix 2 :  6
[[37, 13, 0], [0, 0, 0], [0, 0, 0]]
Matrix 1 :  7
Matrix 2 :  -3
[[37, 13, 6], [0, 0, 0], [0, 0, 0]]
Matrix 1 :  2
Matrix 2 :  3
[[37, 13, 42], [0, 0, 0], [0, 0, 0]]
Matrix 1 :  4
Matrix 2 :  9
[[37, 13, 56], [0, 0, 0], [0, 0, 0]]
Matrix 1 :  7
Matrix 2 :  2
[[37, 13, 56], [35, 0, 0], [0, 0, 0]]
Matrix 1 :  5
Matrix 2 :  7
[[37, 13, 56], [31, 0, 0], [0, 0, 0]]
Matrix 1 :  -1
Matrix 2 :  4
[[37, 13, 56], [35, 0, 0], [0, 0, 0]]
Matrix 1 :  4
Matrix 2 :  1
[[37, 13, 56], [35, 25, 0], [0, 0, 0]]
Matrix 1 :  5
Matrix 2 :  5
[[37, 13, 56], [35, 19, 0], [0, 0, 0]]
Matrix 1 :  -1
Matrix 2 