# Page rank



**Pagerank adalah algoritma yang digunakan oleh mesin pencari seperti Google untuk menilai dan mengurutkan halaman web berdasarkan pentingnya mereka dalam hasil pencarian. Algoritma ini dinamai dari Larry Page**

In [2]:
import numpy as np

In [4]:
A = np.array ([[0,0,1,1/2],[1/3,0,0,0],[1/3,1/2,0,1/2],[1/3,1/2,0,0]])
V0 = np.array ([[0.25],[0.25],[0.25],[0.25]])
V1 = A@V0
print(V1)
V2 = A@V1
print(V2)
V3 = A@V2
print(V3)
V4 = A@V3
print(V4)
V5 = A@V4
print(V5)
V6 = A@V5
print(V6)
V7 = A@V6
print(V7)
V8 = A@V7
print(V8)
V0 = np.array ([[0.3],[0.2],[0.3],[0.2]])
V1 = A@V0
print(V1)
V2 = A@V1
print(V2)
V3 = A@V2
print(V3)
V4 = A@V3
print(V4)
V5 = A@V4
print(V5)
V6 = A@V5
print(V6)
V7 = A@V6
print(V7)
V8 =A@V7
print(V8)


[[0.375     ]
 [0.08333333]
 [0.33333333]
 [0.20833333]]
[[0.4375    ]
 [0.125     ]
 [0.27083333]
 [0.16666667]]
[[0.35416667]
 [0.14583333]
 [0.29166667]
 [0.20833333]]
[[0.39583333]
 [0.11805556]
 [0.29513889]
 [0.19097222]]
[[0.390625  ]
 [0.13194444]
 [0.28645833]
 [0.19097222]]
[[0.38194444]
 [0.13020833]
 [0.29166667]
 [0.19618056]]
[[0.38975694]
 [0.12731481]
 [0.29050926]
 [0.19241898]]
[[0.38671875]
 [0.12991898]
 [0.28978588]
 [0.19357639]]
[[0.4]
 [0.1]
 [0.3]
 [0.2]]
[[0.4       ]
 [0.13333333]
 [0.28333333]
 [0.18333333]]
[[0.375     ]
 [0.13333333]
 [0.29166667]
 [0.2       ]]
[[0.39166667]
 [0.125     ]
 [0.29166667]
 [0.19166667]]
[[0.3875    ]
 [0.13055556]
 [0.28888889]
 [0.19305556]]
[[0.38541667]
 [0.12916667]
 [0.29097222]
 [0.19444444]]
[[0.38819444]
 [0.12847222]
 [0.29027778]
 [0.19305556]]
[[0.38680556]
 [0.12939815]
 [0.29016204]
 [0.19363426]]


In [5]:
A = np.array ([[0.3],[0.2],[0.3],[0.2]])
print(f'matrik A:{A}')

jumlah_matriks = 5

toleransi = 0.05
def hitung_error(matriks1, matriks2):
    error_absolut = np.abs(matriks1 - matriks2)
    error_relatif = np.abs((matriks1 - matriks2) / matriks1)
    return error_absolut, error_relatif

for i in range(jumlah_matriks):
    matriks_acak = np.random.uniform([[0.25],[0.25],[0.25],[0.25]])
    print(f'matrik acak:{matriks_acak}')

    # Menghitung error
    error_absolut, error_relatif = hitung_error(A, matriks_acak)

    within_tolerance = error_relatif < toleransi

    print()
    print(f"Matriks {i+1}:")
    print("Matriks Acak:", matriks_acak)
    print("Error Absolut:", error_absolut)
    print("Error Relatif:", error_relatif)
    print("Within Tolerance:", within_tolerance)
    print()

matrik A:[[0.3]
 [0.2]
 [0.3]
 [0.2]]
matrik acak:[[0.55027704]
 [0.50578051]
 [0.66675316]
 [0.62008691]]

Matriks 1:
Matriks Acak: [[0.55027704]
 [0.50578051]
 [0.66675316]
 [0.62008691]]
Error Absolut: [[0.25027704]
 [0.30578051]
 [0.36675316]
 [0.42008691]]
Error Relatif: [[0.8342568 ]
 [1.52890254]
 [1.22251053]
 [2.10043455]]
Within Tolerance: [[False]
 [False]
 [False]
 [False]]

matrik acak:[[0.84938011]
 [0.49309276]
 [0.70695093]
 [0.9883193 ]]

Matriks 2:
Matriks Acak: [[0.84938011]
 [0.49309276]
 [0.70695093]
 [0.9883193 ]]
Error Absolut: [[0.54938011]
 [0.29309276]
 [0.40695093]
 [0.7883193 ]]
Error Relatif: [[1.83126702]
 [1.46546379]
 [1.3565031 ]
 [3.94159648]]
Within Tolerance: [[False]
 [False]
 [False]
 [False]]

matrik acak:[[0.32070619]
 [0.48072821]
 [0.27754318]
 [0.36288907]]

Matriks 3:
Matriks Acak: [[0.32070619]
 [0.48072821]
 [0.27754318]
 [0.36288907]]
Error Absolut: [[0.02070619]
 [0.28072821]
 [0.02245682]
 [0.16288907]]
Error Relatif: [[0.06902065]
 [1.4