**# tugas determinant**

**determinant adalah konsep penting dalam aljabar linier yang berfungsi yang berkerja pada matrix persegi dan menghasilkan nilai skalar.  Determinan memiliki beberapa fungsi penting, diantaranya:**

**Menentukan apakah suatu matriks singular atau tidak singular , Menghitung volume atau luas yang diubah oleh transformasi linear ,
Menyelesaikan sistem persamaan linear , Menghitung kofaktor dan minor**

**#eksperimen**

**determinat tersebut menggunakan libary numpy untuk menghitung semua matrix dari A sampai J determinant adalah nilai yang di peroleh dalam perkalian entri-entri tertentu pada matriks yang memenuhi kofaktor tertentu. Program ini mendefinisikan 7 matriks yaitu A sampai J kemudian menghitung determinan menggunakan fungsi np.linalg.det() dan print untuk menampilkan hasilnya dari matrix tersebut.**

In [ ]:
import numpy as np

In [ ]:
#matrix
A= np.array(([1,0],[0,1]))
B= np.array(([1,0,0],[0,1,0],[0,0,1]))
C= np.array(([1,2,1],[3,1,2],[2,1,2]))
D= np.array(([3,1,2],[1,2,1],[2,1,2]))
E= np.array(([1,2,1],[2,4,2],[2,1,2]))
F= np.array(([1,2,1],[2,4,2],[2,4,3]))
G= np.array(([6,2,4],[2,4,2],[4,2,3]))
H= np.array(([6,8],[4,2]))
I= np.array(([6,8],[2,1]))
J= np.array(([6,4],[4,1]))

det_A=np.linalg.det(A)
det_B=np.linalg.det(B)
det_C=np.linalg.det(C)
det_D=np.linalg.det(D)
det_E=np.linalg.det(E)
det_F=np.linalg.det(F)
det_G=np.linalg.det(G)
det_H=np.linalg.det(H)
det_I=np.linalg.det(I)
det_J=np.linalg.det(J)

print(det_A)
print(det_B)
print(det_C)
print(det_D)
print(det_E)
print(det_F)
print(det_G)
print(det_H)
print(det_I)
print(det_J)

1.0
1.0
-3.000000000000001
3.000000000000001
0.0
0.0
4.000000000000005
-19.999999999999996
-9.999999999999998
-9.999999999999998


In [ ]:
import numpy as np
n = 3

upper_matrix = np.triu(np.ones((n, n)), k=0)
print("Matriks segitiga atas:")
print(upper_matrix)

lower_matrix = np.tril(np.ones((n, n)), k=0)
print("\nMatriks segitiga bawah:")
print(lower_matrix)

determinant_upper = np.linalg.det(upper_matrix)
print("\nDeterminan matriks segitiga atas:", determinant_upper)

determinant_lower = np.linalg.det(lower_matrix)
print("Determinan matriks segitiga bawah:", determinant_lower)

Matriks segitiga atas:
[[1. 1. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]

Matriks segitiga bawah:
[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]

Determinan matriks segitiga atas: 1.0
Determinan matriks segitiga bawah: 1.0


In [ ]:
#Mtriks Segitiga atas
import numpy as np
k= np.array([[1,2,3],[0,2,1],[0,0,1]])
print(k)
k=np.linalg.det(k)
print(f'Determinannya:',{k})

[[1 2 3]
 [0 2 1]
 [0 0 1]]
Determinannya: {2.0}


In [ ]:
l= np.array([[1,0,0],[2,1,0],[4,1,3]])
print(l)
l=np.linalg.det(l)
print(f'Determinannya:',{l})

[[1 0 0]
 [2 1 0]
 [4 1 3]]
Determinannya: {2.9999999999999996}


Determinan matrix C det = (AB)

In [ ]:
import numpy as np
a= np.array([[2,1],[1,1]])
print(a)
a=np.linalg.det(a)
print(f'Determinannya:',{a})
print()
b= np.array([[1,1],[1,1]])
print(b)
b=np.linalg.det(b)
print(f'Determinannya:',{b})

[[2 1]
 [1 1]]
Determinannya: {1.0}

[[1 1]
 [1 1]]
Determinannya: {0.0}


In [ ]:
C=np.array([[3,3],[2,2]])
print(C)
C=np.linalg.det(C)
print(f'Determinannya:',{C})

[[3 3]
 [2 2]]
Determinannya: {0.0}


In [ ]:
from google.colab import drive
drive.mount('/content/drive')